DROP DATABASE DISCOSOUND;

CREATE DATABASE DISCOSOUND;

USE DISCOSOUND;

CREATE TABLE USUARIO (
DNI VARCHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (20),
APELLIDO VARCHAR (20),
NOMUSU VARCHAR (20) not null,
FECHANAC DATE,
EMAIL VARCHAR(40),
CONTRASEINA varchar(20) not null
);

CREATE TABLE ADMINISTRADOR (
DNIADMIN VARCHAR(9) PRIMARY KEY,
NOMDISCOTECA VARCHAR(20),
FOREIGN KEY (DNIADMIN) REFERENCES usuario (dni) on delete cascade on update cascade
);

CREATE TABLE CLIENTE (
DNICLIENTE VARCHAR(9) PRIMARY KEY,
GENERO VARCHAR (10),
FOREIGN KEY (DNICLIENTE) REFERENCES usuario (dni) on delete cascade on update cascade
);

CREATE TABLE DISCOTECA (
CODIGODISC VARCHAR (20) PRIMARY KEY,
NOMBRE VARCHAR (20),
DIRECCION VARCHAR (50),
AFORO INT);

CREATE TABLE ENTRADA (
CODENTRADA VARCHAR(20) PRIMARY KEY,
NOMEVENTO VARCHAR(20),
NOMDJ VARCHAR(20) default 'SORPRESA',
PRECIO INT,
CATEGORIA VARCHAR(20),
CANTCONSUMI INT,
FECHA DATE,
DIFERENCIAPRECIOMUJER INT,
CODIGODISC VARCHAR (20),
FOREIGN KEY (CODIGODISC) REFERENCES DISCOTECA (CODIGODISC) on delete cascade on update cascade
);

CREATE TABLE COMPRA (
DNICLIENTE VARCHAR(9),
CODENTRADA VARCHAR(20),
METODOPAGO VARCHAR(20),
CANTIDAD INT, 
GENERO VARCHAR(10),
TELEFONO INT, 
PRIMARY KEY (DNICLIENTE, CODENTRADA),
FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTE (DNICLIENTE),
FOREIGN KEY (CODENTRADA) REFERENCES ENTRADA (CODENTRADA));

select * from cliente