DROP DATABASE DISCOSOUND;

CREATE DATABASE DISCOSOUND;

USE DISCOSOUND;

CREATE TABLE USUARIO (
DNI VARCHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (20),
APELLIDO VARCHAR (20),
NOMUSU VARCHAR (20),
FECHANAC DATE,
EMAIL VARCHAR(40));

CREATE TABLE ADMINISTRADOR (
DNIADMIN VARCHAR(9) PRIMARY KEY,
NOMDISCOTECA VARCHAR(20));

CREATE TABLE CLIENTE (
DNICLIENTE VARCHAR(9) PRIMARY KEY,
GENERO VARCHAR (10));

CREATE TABLE ENTRADA (
CODENTRADA VARCHAR(20) PRIMARY KEY,
NOMEVENTO VARCHAR(20),
NOMDJ VARCHAR(20),
PRECIO INT,
CATEGORIA VARCHAR(20),
CANTCONSUMI INT,
FECHA DATE,
DIFERENCIAPRECIOMUJER INT);

CREATE TABLE COMPRA (
DNICLIENTE VARCHAR(9),
CODENTRADA VARCHAR(20),
METODOPAGO VARCHAR(20),
CANTIDAD INT, 
PRIMARY KEY (DNICLIENTE, CODENTRADA),
FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTE (DNICLIENTE),
FOREIGN KEY (CODENTRADA) REFERENCES ENTRADA (CODENTRADA));

CREATE TABLE DISCOTECA (
CODIGO VARCHAR (20) PRIMARY KEY,
NOMBRE VARCHAR (20),
DIRECCION VARCHAR (50),
AFORO INT);

